version: '3.8'

services:
  phoenix:
    container_name: phoenix
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006"
      - "4317:4317"
    volumes:
      - phoenix_data:/data
    networks:
      - poker-net
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:6006/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      - PHOENIX_LOG_LEVEL=debug
      - PHOENIX_TELEMETRY_ENABLED=true

  poker_bot:
    container_name: poker_bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PHOENIX_HOST=phoenix
      - PHOENIX_PORT=6006
      - PHOENIX_GRPC_PORT=4317
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
    depends_on:
      phoenix:
        condition: service_healthy
    volumes:
      - ./poker_bot/src/poker_bot:/app/poker_bot
      - ./data:/app/data
    networks:
      - poker-net
    stdin_open: true
    tty: true
    command: ["/bin/bash", "-c", "sleep 5 && /app/scripts/start.sh"]

networks:
  poker-net:
    name: poker-net
    driver: bridge

volumes:
  phoenix_data:
